# Very basic Docker Compose file for a PostgreSQL database and Adminer - will change it in the future for more complex setup
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pgdata:
